### ISSUE TITLE
NoClassDefFoundError ?

### ISSUE THREAD

**Issue by ato2** [transpect/docx2tex#101]
An clue ?
~\Downloads\docx2tex-1.8-release\docx2tex > ./d2t 1-ang.docx
starting docx2tex
Errors encountered while running docx2tex. Please see C:/Users/ato/Downloads/docx2tex-1.8-release/docx2tex/1-ang.log for details.
~\Downloads\docx2tex-1.8-release\docx2tex > cat 1-ang.log   
Exception in thread "main" java.lang.NoClassDefFoundError: javax/naming/Context
        at org.apache.logging.log4j.core.lookup.Interpolator.<init>(Interpolator.java:113)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.<init>(AbstractConfiguration.java:133)
        at org.apache.logging.log4j.core.config.NullConfiguration.<init>(NullConfiguration.java:32)
        at org.apache.logging.log4j.core.LoggerContext.<clinit>(LoggerContext.java:85)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(ClassLoaderContextSelector.java:254)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:218)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:136)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:123)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:117)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:150)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:137)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:55)
        at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:47)
        at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:33)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:363)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
        at com.xmlcalabash.drivers.Main.<init>(Main.java:74)
        at com.xmlcalabash.drivers.Main.main(Main.java:82)
Caused by: java.lang.ClassNotFoundException: javax.naming.Context
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 20 more
~\Downloads\docx2tex-1.8-release\docx2tex > java --version  
openjdk 14 2020-03-17
OpenJDK Runtime Environment AdoptOpenJDK (build 14+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 14+36, mixed mode)

**Comment by gimsieke** [comment]
@mkraetke Hmm, maybe switch to the [Saxon 10 based Calabash 1.3](https://github.com/transpect/calabash-frontend/blob/saxon10/calabash.sh) that doesn’t use Log4j any more?

**Comment by mkraetke** [comment]
@ato2 thanks for reporting this. Does this happen with any DOCX file?
