### ISSUE TITLE
d2t does not play well with filenames containing whitespace

### ISSUE THREAD

**Issue by zopyx** [transpect/docx2tex#18]
```
./d2t "6 Interferometrische Sensoren/160228 6_Interferometrische Sensoren.docx" 
./d2t: line 87: [: too many arguments
./d2t: line 121: [: too many arguments
./d2t: line 143: $LOG: ambiguous redirect
./d2t: line 146: [: too many arguments
starting docx2tex
./d2t: line 167: $LOG: ambiguous redirect
Errors encountered while running docx2tex. Please see /Users/ajung/src/docx2tex/6 Interferometrische Sensoren/6
Interferometrische
160228
6_Interferometrische
Sensoren.docx
.docx.d2t.log for details.
```

**Comment by gimsieke** [comment]
Please try the latest commit.

**Comment by zopyx** [comment]
It seems to work better but not solid enough e.g. with paths containing whitespace in a directory name (independent of using quotes or bash escaping).

```
Suxmac:docx2tex ajung$ ./d2t "a b/a b.docx"
starting docx2tex
Errors encountered while running docx2tex. Please see /Users/ajung/src/docx2tex/a b/a_b.d2t.log for details.
Suxmac:docx2tex ajung$ ./d2t a\ b/a\ b.docx 
starting docx2tex
Errors encountered while running docx2tex. Please see /Users/ajung/src/docx2tex/a b/a_b.d2t.log for details.
````

```
Suxmac:docx2tex ajung$ cat "/Users/ajung/src/docx2tex/a b/a_b.d2t.log" 
Exception in thread "main" java.lang.IllegalArgumentException: Illegal character in path at index 27: /Users/ajung/src/docx2tex/a b/a_b.tex
	at java.net.URI.create(URI.java:852)
	at java.net.URI.resolve(URI.java:1036)
	at com.xmlcalabash.util.UserArgs.addOutput(UserArgs.java:257)
	at com.xmlcalabash.util.ParseArgs.parse(ParseArgs.java:112)
	at com.xmlcalabash.drivers.Main.run(Main.java:92)
	at com.xmlcalabash.drivers.Main.main(Main.java:83)
Caused by: java.net.URISyntaxException: Illegal character in path at index 27: /Users/ajung/src/docx2tex/a b/a_b.tex
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3063)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 5 more
```

**Comment by gimsieke** [comment]
That’s what I stated in the commit message of 5c049f9.

**Comment by zopyx** [comment]
The error persists even with a fresh docx2tex checkout including all submodules.

**Comment by gimsieke** [comment]
which is to be expected, as I didn’t fix whitespace in paths, and that’s what I said in the commit message

**Comment by gimsieke** [comment]
Try updating to the latest commit, including the updated xproc-util submodule.

**Comment by mkraetke** [comment]
No reply from @zopyx, so I've tested d2t with spaces in directory and filename and the issue doesn't occur anymore. Therefore I'll close this issue.
