### ISSUE TITLE
Beginner's question on how to use docx2tex

### ISSUE THREAD

**Issue by Eidonko** [transpect/docx2tex#47]
Dear Sirs/Madams,
I need to convert a number of docx files to LaTeX so I have downloaded your tool on my xubuntu 19.04 laptop. Regrettably, when I try to run your code an error message is displayed:

    $ ./d2t ~/Documents/Introduction.docx 
    starting docx2tex
    Errors encountered while running docx2tex. Please see /home/eidon/Documents/Introduction.d2t.log for details.
    $ cat Introduction.d2t.log
    ./d2t: line 203: /home/eidon/packages/docx2tex-master/calabash/calabash.sh: No such file or directory

From this I understood that I needed to install calabash, which I did by running

    $ java -jar xmlcalabash-1.1.27-99.jar

Despite this, the error is still there. Would you be so kind as to help me? Thank you very much!

Kind regards,
Eidon

**Comment by mkraetke** [comment]
Hi Eidon,
thanks for you report. It seems that one or more submodules are missing. When you download or clone the code of this repository, the Git submodules are not included. Therefore we provide [docx2tex releases](https://github.com/transpect/docx2tex/releases) which are considered as stable and already include submodules. If you want to use Git, then you should always clone with submodules.
```
git clone https://github.com/transpect/docx2tex --recursive
```
How did you download word2tex and does this solve your issue?
best, Martin

**Comment by Eidonko** [comment]
Dear Martin,

thank you very much for your kind reply. I downloaded https://github.com/transpect/docx2tex/releases/download/v.1.2/docx2tex-1.2-release.zip <https://github.com/transpect/docx2tex/releases/download/v.1.2/docx2tex-1.2-release.zip> and run d2t on one of my documents. Something still goes wrong -- possibly due to my java installation??

$ ./d2t ~/Documents/TDR-Word/"edited name".docx
starting docx2tex
Errors encountered while running docx2tex. Please see /home/vdflorio/Documents/TDR-Word/"edited name".log for details.
vdflorio@vdflorio-VirtualBox:~/packages/docx2tex$ cat /home/vdflorio/Documents/TDR-Word/"edited name".d2t.logException in thread "main" java.lang.NoClassDefFoundError: javax/activation/DataSource
at java.base/java.lang.Class.getDeclaredMethods0 <http://java.base/java.lang.Class.getDeclaredMethods0>(Native Method)
at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166) <http://java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)>
at java.base/java.lang.Class.getMethodsRecursive(Class.java:3307) <http://java.base/java.lang.Class.getMethodsRecursive(Class.java:3307)>
at java.base/java.lang.Class.getMethod0(Class.java:3293) <http://java.base/java.lang.Class.getMethod0(Class.java:3293)>
at java.base/java.lang.Class.getMethod(Class.java:2106) <http://java.base/java.lang.Class.getMethod(Class.java:2106)>
at com.xmlcalabash.core.XProcRuntime.initializeSteps(XProcRuntime.java:317)
at com.xmlcalabash.core.XProcRuntime.<init>(XProcRuntime.java:272)
at com.xmlcalabash.drivers.Main.run(Main.java:100)
at com.xmlcalabash.drivers.Main.main(Main.java:83)
Caused by: java.lang.ClassNotFoundException: javax.activation.DataSource
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) <http://java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)>
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) <http://java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)>
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) <http://java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)>
... 9 more

This is the Java I'm using:

$ java --version
openjdk 11.0.3 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu219.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu219.04.1, mixed mode, sharing)

and here's the details about my platform:
$ uname -a
Linux editedname-VirtualBox 5.0.0-20-generic #21-Ubuntu SMP Mon Jun 24 09:32:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Once again I would appreciate very much your help -- thank you very much!

Best regards,
Eidon

-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Jul 10, 2019, 11:03 AM by notifications@github.com:

**Comment by mkraetke** [comment]
Hi Eidon,
under the hood, docx2tex is based on XSLT and XProc. Unfortunately, the XProc processor currently doesn't support Java higher than version 1.8. So I would suggest to downgrade your Java to 1.7 or 1.8, then it should work.
Best, Martin

**Comment by Eidonko** [comment]
Hello Martin,
I see. Okay, thank you very much.
Kind regards,
Eidon

-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Jul 11, 2019, 12:34 PM by notifications@github.com:

**Comment by mkraetke** [comment]
You can now use [docx2tex 1.4](https://github.com/transpect/docx2tex/releases/tag/v1.4). This supports Java from 1.7 to the latest version.
